### PR TITLE
No duplicates in service and room type list

### PR DESCRIPTION
**Pull request by sreycodes**

### CODE REVIEW

**Comment by sreycodes** [comment]
- Make the above checking while editing as well!

**Review by Tejas2805 — COMMENTED** [review]
Please implement the same for EditServiceType and EditRoomType as well. Otherwise looks okay.

**Review by Tejas2805 — COMMENTED** [review]
Looks good. Would like to see some tests though.
So if possible add them too.

**Review by Tejas2805 — APPROVED** [review]

**Comment by sreycodes** [comment]
I will try my level best to do that.

**Pull request merged**
